# Generated by Django 3.2.2 on 2021-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
